ProdajaOpremeZaBilijar/KorpaZaKupovinu/urls.py
from django.urls import path
from . import views

app_name = 'KorpaZaKupovinu'

urlpatterns = [
    path('', views.DetaljiKorpe, name='DetaljiKorpe'),
    path('add/<int:product_id>/', views.AddToCart, name='AddToCart'),
    path('remove/<int:product_id>/', views.RemoveFromCart, name='RemoveFromCart')
]

ProdajaOpremeZaBilijar/Porudzbina/urls.py
from django.urls import path
from . import views

app_name= 'Order'
urlpatterns = [
    path('kreirajporudzbinu/', views.AddOrder, name='AddOrder'),
]

ProdajaOpremeZaBilijar/ProdajaOpremeZaBilijar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('KorpaZaKupovinu/', include('KorpaZaKupovinu.urls', namespace='KorpaZaKupovinu')),
    path('Porudzbina/', include('Porudzbina.urls', namespace='Porudzbina')),
    path('', include('ProdavnicaBilijara.urls', namespace='ProdavnicaBilijara')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProdajaOpremeZaBilijar/ProdavnicaBilijara/urls.py
from django.urls import path
from . import views

app_name = 'prodavnicabilijara'
urlpatterns = [
    path('', views.ListaProizvoda, name='ListaProizvoda'),
    path('<slug:category_slug>/', views.ListaProizvoda, name='ListaProizvodaPoKategoriji'),
    path('<int:id>/<slug:slug>/', views.DetaljiProizvoda, name='DetaljiProizvoda')
]

ProdajaOpremeZaBilijar/KorpaZaKupovinu/models.py
from django.db import models

# Create your models here.

ProdajaOpremeZaBilijar/Porudzbina/models.py
from django.db import models
from ProdavnicaBilijara.models import Product

# Create your models here.


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created_date',)
        verbose_name = 'order'
        verbose_name_plural = 'orders'

    def __str__(self): return f'Order {self.id}'

    def GetTotalPriceOrder(self):
        return sum(item.GetTotalPrice() for item in self.items_order_o.all())
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items_order_o', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items_order_p', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

ProdajaOpremeZaBilijar/ProdavnicaBilijara/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True, db_index=True)
    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self): return self.name
    def ApsolutniURL(self): return reverse('ProdavnicaBilijara:ListaProizvodaPoKategoriji', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='proizvodi/%Y/%m/%D', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'))
        verbose_name_plural = 'products'

    def __str__(self): return self.name
    def ApsolutniURL(self): return reverse('ProdavnicaBilijara:DetaljiProizvoda', args=[self.id, self.slug])

ProdajaOpremeZaBilijar/KorpaZaKupovinu/forms.py
from django import forms
CHOOSE_NUMBER_OF_PRODUCT = [(i, str(i)) for i in range(1, 11)]

class FormaZaDodavanjeProizvodaUKorpu(forms.Form):
    quantity = forms.TypedChoiceField( choices=CHOOSE_NUMBER_OF_PRODUCT, empty_value=1,coerce=int ) # convert to int
    add_to_quantity = forms.BooleanField(required=False, initial=True, widget=forms.HiddenInput)

ProdajaOpremeZaBilijar/Porudzbina/forms.py
from django import forms;
from .models import Order

class OrderForm(forms.ModelForm):
   class Meta:
    model = Order
    fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

ProdajaOpremeZaBilijar/KorpaZaKupovinu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ProdavnicaBilijara.models import Product
from .korpa import Korpa
from .forms import FormaZaDodavanjeProizvodaUKorpu

# Create your views here.

@require_POST
def AddToCart(request, product_id):
    cart = Korpa(request)
    product = get_object_or_404(Product, id=product_id)
    form = FormaZaDodavanjeProizvodaUKorpu(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.Add(product=product, quantity=cleaned_data['quantity'], add_to_quantity=cleaned_data['add_to_quantity'])
    
    return redirect('KorpaZaKupovinu:DetaljiKorpe')

@require_POST
def RemoveFromCart(request, product_id):
    print('product', product_id)
    cart = Korpa(request)
    product = get_object_or_404(Product, id=product_id)
    
    cart.Remove(product)
    return redirect('KorpaZaKupovinu:DetaljiKorpe')

def DetaljiKorpe(request):
    cart = Korpa(request)
    for item in cart: 
        print('item', item)
        item['formazaazuriranjekolicine'] = FormaZaDodavanjeProizvodaUKorpu(
            initial={ 'quantity': 1, 'add_to_quantity': True }
        )
    return render(request, 'KorpaZaKupovinu/detail.html', { 'cart': cart })

ProdajaOpremeZaBilijar/Porudzbina/views.py
from django.shortcuts import render

from KorpaZaKupovinu.korpa import Korpa
from .models import OrderItem
from .forms import OrderForm

# Create your views here.

def AddOrder(request):
    cart = Korpa(request)
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                print('cart', item)
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])

            cart.DeleteCartFromSession()
            return render(request, 'Porudzbina/created.html', { 'order': order })
        
    else: 
        form = OrderForm()
    
    return render(request, 'Porudzbina/create.html', { 'cart': cart, 'form': form })
   

ProdajaOpremeZaBilijar/ProdavnicaBilijara/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

from KorpaZaKupovinu.forms import FormaZaDodavanjeProizvodaUKorpu

from KorpaZaKupovinu.korpa import Korpa

def ListaProizvoda(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    cart = Korpa(request)

    return render(request, 'ProdavnicaBilijara/list.html',
                  { 'category': category, 'categories': categories,
                   'products': products, 'cart': cart })

def DetaljiProizvoda(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)

    cart = Korpa(request)
    formazadodavanjeproizvodaukorpu = FormaZaDodavanjeProizvodaUKorpu()

    return render(request, 'ProdavnicaBilijara/detail.html',
                  { 'product': product, 'formazadodavanjeproizvodaukorpu': formazadodavanjeproizvodaukorpu, 'cart': cart })
 
# Create your views here.

ProdajaOpremeZaBilijar/KorpaZaKupovinu/templates/KorpaZaKupovinu/detail.html
{% extends "ProdavnicaBilijara/base.html" %}
{% load static %}
{% block title %} Korpa za kupovinu {% endblock %}
{% block content %}
    <h1>Korpa za kupovinu</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Proizvod</th><th>Kolicina</th>
                <th>Ukloni iz korpe</th><th>Cena po komadu</th><th>Cena</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}

                {% with product=item.product %}
                    <tr>
                        <!-- <td>
                            <a href="{{ product.ApsolutniURL }}">
                                <img src='{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}' alt="">
                            </a>
                        </td> -->
                        <td>{{ product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <form action='{% url "KorpaZaKupovinu:RemoveFromCart" product_id=product.id %}' method="POST">
                                <input type="submit" value="Ukloni">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}

            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.GetTotalPrice }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href='{% url "ProdavnicaBilijara:ListaProizvoda" %}' class="button light">Nastavak kupovine</a>
        <!-- Here we will add link to check order-->
        <a href='{% url "Order:AddOrder" %}' class="button">Provera</a>
    </p>
{% endblock %}

ProdajaOpremeZaBilijar/Porudzbina/templates/Porudzbina/create.html
{% extends "ProdavnicaBilijara/base.html" %}
{% block title %}
    Provera
{% endblock %}
{% block content %}
    <h1>Provera</h1>
    <div class="order-info">
        <h3>Vasa porudzbina</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>&euro;{{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p> Total: ${{ cart.GetTotalPrice }}</p>
    </div>
    <form method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Porucivanje"></p>
        {% csrf_token %}
    </form>
{% endblock %}

ProdajaOpremeZaBilijar/Porudzbina/templates/Porudzbina/created.html
{% extends "ProdavnicaBilijara/base.html" %}
{% block title %}
    Hvala Vam
{% endblock %}
{% block content %}
    <h1>HVALA</h1>
    <p>Vasa porudzbina broj <strong>{{ order.id }}</strong> je uspesno evidentirana</p>
{% endblock %}

ProdajaOpremeZaBilijar/ProdavnicaBilijara/templates/ProdavnicaBilijara/base.html
{% load static  %}
<link rel="stylesheet" type="text/css" href="{% static 'ProdavnicaBilijara/css/base.css' %}">

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Prodavnica Bilijara{% endblock %}</title>
    <!-- You may include your static files or stylesheets here -->
</head>
<body>
    <div id="header">
        <a href="/" class="logo">Prodaja Opreme Za Bilijar</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {{ cart|length }}
                {% with numberOfItems=cart|length %}
                    {% if numberOfItems > 0 %}
                        U korpi se nalazi:
                            <a href='{% url "KorpaZaKupovinu:DetaljiKorpe" %}'>
                                {{ numberOfItems }} kom, ukupna cena
                                &euro;{{ cart.GetTotalPrice }}
                            </a>
                    {% else %}
                            Korpa je prazna.
                    {% endif %}
                {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

ProdajaOpremeZaBilijar/ProdavnicaBilijara/templates/ProdavnicaBilijara/detail.html
{% extends "ProdavnicaBilijara/base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src='{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}' alt="">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.ApsolutniURL }}">{{ product.category }}</a>
        </h2>
        <p class="price">&euro;{{ product.price }}</p>
        <form action='{% url "KorpaZaKupovinu:AddToCart" product.id %}' method="POST">
            {{ formazadodavanjeproizvodaukorpu }}
            {% csrf_token %}
            <input type="submit" value="Dodaj u korpu">
        </form>
        {{ product.description|linebreaks }}
        <!-- <p id="demo">{% url 'KorpaZaKupovinu:AddToCart' product.id %}</p> -->
    </div>
{% endblock %}

ProdajaOpremeZaBilijar/ProdavnicaBilijara/templates/ProdavnicaBilijara/list.html
{% extends "ProdavnicaBilijara/base.html" %}
{% load static %}
{% block title %} {% if category %}{{ category.name }}{% else %}Proizvodi{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>
            Kategorije
        </h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href='{% url "ProdavnicaBilijara:ListaProizvoda" %}'>Svi proizvodi</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.ApsolutniURL }}">{{ c.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Proizvodi{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.ApsolutniURL }}">
                    <img src='{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}' alt="">
                </a>
                <a href="{{ product.ApsolutniURL }}">{{ product.name }}</a>
                <br>
                &euro;{{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}